development:
  adapter: postgresql
  encoding: unicode
  database: achaw_development
  pool: 5
  username: adamoates
  password: messiah4891

test:
  adapter: postgresql
  encoding: unicode
  database: achaw_development_test
  pool: 5
  username: adamoates
  password: messiah4891